### ISSUE TITLE
No repacker included.

### ISSUE THREAD

**Issue by E2PARA** [Ekey/CE.DAT.Tool#1]
Hello, @Ekey , i try to mod conflict games using your tools, and it was awesome, but sadly there's no repacker for it and i cant make any changes to the game mission such as object et cetera, if you are about to do the reapcker, im sure it will be helpful to mod this type of old era games, also, if you dont mind, can you make the 'unpacker' and 'repacker' tools for Pivotal Games '.sch' sound files, because vgmstream plugins for foobar can't read most of the .sch's, thank you.

**Comment by Ekey** [comment]
Hi. Maybe when I have more free time I will make a packer

**Comment by E2PARA** [comment]
> Hi. Maybe when I have more free time I will make a packer

Thank you for your respond, but yeah, can you also do the tools to unpack and repack the pivotal games sound (.sch) too? ... Im sorry if its too much to request.
